# Generated by Django 6.0.7 on 2026-08-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_candidateprofile_is_active_employerprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
